spring:
  profiles:
    active: development
---
spring:
  profiles: development
server:
  port: 8011
eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8080/eureka/
---
spring:
  profiles: cloud
server:
  port: 8022
eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8080/eureka/
---